name: Build OS package

on:
  push:
    tags:
      - '*'

env:
  VERSION_TAG: ${{ startsWith(github.event.ref, 'refs/tags/') && github.ref_name || format('0.{0}', github.run_number) }}  

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
      env:
        DISTRO: debian:bookworm
    steps:
      - uses: actions/checkout@v4

      - name: Install Sudo
        run: apt-get update && apt-get -y install sudo

      - name: Set up Docker
        uses: docker/setup-docker-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Build Debian Package
        run: bash ./dev-scripts/build-debian-pkg

      - name: Bundle Packages for Release
        run: bash ./.github/workflows/pack-artifact

      - name: Attach Package to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /output/packages.zip
          asset_name: ${{ github.event.repository.name }}-debian-bookworm.zip
          tag: ${{ github.ref }}
